Feature
dmiyakoshi/planet_app pull request #1
Opened 2021-09-20 04:12 UTC by dmiyakoshi

2021-09-20 20:44 UTC, kazu-taka requested changes
@dmiyakoshi 
コメントしたので修正お願いします🙏

2021-09-20 20:44 UTC, kazu-taka commented on database/migrations/2021_09_19_083819_create_planets_table.php
> +            $table->string('name', 7);
@dmiyakoshi 
今は桁数指定しても問題ないですが、万が一新しい惑星が発見された時に桁数オーバーする場合があるので、桁数指定は削除して下さい👍

2021-09-20 20:44 UTC, kazu-taka commented on database/seeders/PlanetSeeder.php
> +        ],
@dmiyakoshi 
配列の入れ子の場合は、以下の方が見やすいと思うので修正お願いします！
```php
        $params = [
            [
                'name_ja' => '水星',
                'name' => 'MERCURY',
                'radius' => 2439,
                'weight' => 3310
            ],
            [
                // 省略
            ],
        ]
```

2021-09-20 20:44 UTC, kazu-taka commented on resources/views/planets/create.blade.php
> +        <p>重量 <input type="number" name="weight" value="{{ old('planet->weight') }}"></p>
@dmiyakoshi 
createの場合は`planet-`が不要になります！

2021-09-20 20:44 UTC, kazu-taka commented on resources/views/planets/index.blade.php
> +                </form> --}}
@dmiyakoshi 
不要なコードは削除お願いします！

2021-09-21 01:20 UTC, dmiyakoshi commented on database/seeders/PlanetSeeder.php
> +        ],
入れ子のインデントを修正しました。

2021-09-21 01:20 UTC, dmiyakoshi commented on database/migrations/2021_09_19_083819_create_planets_table.php
> +            $table->string('name', 7);
桁数指定は削除しました。

2021-09-21 01:21 UTC, dmiyakoshi commented on resources/views/planets/create.blade.php
> +        <p>重量 <input type="number" name="weight" value="{{ old('planet->weight') }}"></p>
planetを消しました。

2021-09-21 01:22 UTC, dmiyakoshi commented on resources/views/planets/index.blade.php
> +                </form> --}}
コメントのコードを消しました。

2021-09-21 02:02 UTC, kazu-taka commented
@dmiyakoshi 
問題ないのでマージしてOKです👍
![LGTM](https://image.lgtmoon.dev/75073)

2021-09-22 02:08 UTC, merged